// Generated by scripts/build-official-plugins.mjs. Do not edit manually.
export const OFFICIAL_X_PACKAGE_TRUST = Object.freeze({
  "pluginId": "streamfold.x",
  "version": "1.1.5",
  "packageFile": "streamfold.x-1.1.5.streamfold-plugin",
  "packageHash": "sha256:229e8b7388659abd93952dc491365e17885358a2aca9f5c74416a7a01f2fd589",
  "contentHash": "sha256:926ae8ad4ac257b3490597be000101493aab6a7c6861432cfd0ea65d2d8227a6",
  "publisherKeyId": "streamfold-official",
  "publisherPublicKey": "MCowBQYDK2VwAyEAkzMRMukUCfnt9MHqTNEEr8bU7gzEc2UFofHNk4aSX4Y="
} as const)
