// Generated by scripts/build-official-plugins.mjs. Do not edit manually.
export const OFFICIAL_X_PACKAGE_TRUST = Object.freeze({
  "pluginId": "streamfold.x",
  "version": "1.2.0",
  "packageFile": "streamfold.x-1.2.0.streamfold-plugin",
  "packageHash": "sha256:8bb45e4c8ebf150ea92d7c5ca04263c064377d2f1021dcbdfb6d0d88e13bcfdc",
  "contentHash": "sha256:4acc4d9fa65512e7a58482831a504b8b46759c2a4111787a8e0de4ba44371314",
  "publisherKeyId": "streamfold-official",
  "publisherPublicKey": "MCowBQYDK2VwAyEAkzMRMukUCfnt9MHqTNEEr8bU7gzEc2UFofHNk4aSX4Y="
} as const)
